default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: adfego
  username: postgres
  password: root

production:
  <<: *default
  database: adfego_production
  username: adfego
  password: <%= ENV['ADFEGO_DATABASE_PASSWORD'] %>
